### ISSUE TITLE
Fluent won't work with Django >= 1.8.4

### ISSUE THREAD

**Issue by moggers87** [potatolondon/fluent-2.0#3]
Saving a model with a translatable field when using Django >= 1.8.4, the following exception is raised:
```
AttributeError: 'TranslatableContent' object has no attribute 'pk'
```

Relevant release note:
> Moved the unsaved model instance assignment data loss check to Model.save() to allow easier usage of in-memory models (#25160).

The new save code checks if a field is defined as a relation and then checks the object on that field for a non-None `pk` attribute. [Link to code](https://github.com/django/django/blob/1.8.4/django/db/models/base.py#L668)

A hacky work around is to define a `pk` attribute on `TranslatableContent` and set it to some value. Any better ideas?

**Comment by moggers87** [comment]
N.B. the PK checks happen before `pre_save` is called on the field.

**Comment by moggers87** [comment]
This is fixed now
